/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"
#include "TROOT.h"

#include "RooKrTest.hh"
#include "RooAbsReal.h"
#include <math.h>
#include "TMath.h"

RooKrTest::RooKrTest(const char *name, const char *title,
                     RooAbsReal &_KE) : RooAbsPdf(name, title),
                                        KE("KE", "KE", this, _KE)
{
}

RooKrTest::RooKrTest(const RooKrTest &other, const char *name) : RooAbsPdf(other, name),
                                                                 KE("KE", this, other.KE)
{
}

Double_t RooKrTest::evaluate() const
{

    return TMath::Exp(-KE * KE);
}
