/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOKRTEST
#define ROOKRTEST

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"

class RooKrTest : public RooAbsPdf
{
public:
  RooKrTest(){};
  RooKrTest(const char *name, const char *title,
            RooAbsReal &_KE);
  RooKrTest(const RooKrTest &other, const char *name = 0);
  virtual TObject *clone(const char *newname) const { return new RooKrTest(*this, newname); }
  inline virtual ~RooKrTest(){};

protected:
  RooRealProxy KE;
  // RooRealProxy Q;
  // RooRealProxy mbeta;

  Double_t evaluate() const;

  //  ClassDef(RooRealTritiumSpectrum,2) // Your description goes here...
};

#endif
