/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef DISTORTEDTRITIUMSPECTRUM
#define DISTORTEDTRITIUMSPECTRUM

#include "RooRealProxy.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"

// namespace Phylloxera
// {
class DistortedTritiumSpectrum : public RooAbsPdf
{
public:
  DistortedTritiumSpectrum(){};
  DistortedTritiumSpectrum(const char *name, const char *title,
                      RooAbsReal &_KE,
                      RooAbsReal &_Q,
                      RooAbsReal &_mbeta);
  DistortedTritiumSpectrum(const DistortedTritiumSpectrum &other, const char *name = 0);
  virtual TObject *clone(const char *newname) const { return new DistortedTritiumSpectrum(*this, newname); }
  // inline virtual ~DistortedTritiumSpectrum(){};

protected:
  RooRealProxy KE;
  RooRealProxy Q;
  RooRealProxy mbeta;

  Double_t evaluate() const;

  ClassDef(DistortedTritiumSpectrum, 1) // Your description goes here...
};
// }

#endif
