/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef REALTRITIUMSPECTRUM
#define REALTRITIUMSPECTRUM

#include "RooRealProxy.h"
#include "RooAbsReal.h"
#include "RooAbsPdf.h"

namespace Phylloxera
{
class RealTritiumSpectrum : public RooAbsPdf
{
public:
  RealTritiumSpectrum(){};
  RealTritiumSpectrum(const char *name, const char *title,
                      RooAbsReal &_KE,
                      RooAbsReal &_Q,
                      RooAbsReal &_mbeta);
  RealTritiumSpectrum(const RealTritiumSpectrum &other, const char *name = 0);
  virtual TObject *clone(const char *newname) const { return new RealTritiumSpectrum(*this, newname); }
  // inline virtual ~RealTritiumSpectrum(){};

protected:
  RooRealProxy KE;
  RooRealProxy Q;
  RooRealProxy mbeta;

  Double_t evaluate() const;

  //  ClassDef(RealTritiumSpectrum,2) // Your description goes here...
};
}

#endif
