/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOSIMPLETRITIUMSPECTRUM
#define ROOSIMPLETRITIUMSPECTRUM

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooAbsReal.h"

class RooSimpleTritiumSpectrum : public RooAbsPdf
{
public:
  RooSimpleTritiumSpectrum(){};
  RooSimpleTritiumSpectrum(const char *name, const char *title,
                           RooAbsReal &_KE,
                           RooAbsReal &_Q,
                           RooAbsReal &_mbeta);
  RooSimpleTritiumSpectrum(const RooSimpleTritiumSpectrum &other, const char *name = 0);
  virtual TObject *clone(const char *newname) const { return new RooSimpleTritiumSpectrum(*this, newname); }
  inline virtual ~RooSimpleTritiumSpectrum(){};

protected:
  RooRealProxy KE;
  RooRealProxy Q;
  RooRealProxy mbeta;

  Double_t evaluate() const;

//  ClassDef(RooRealTritiumSpectrum,2) // Your description goes here...
};


#endif
